
import { Link } from "react-router-dom";

function About() {
  return (
   <div>sobre nosotros

      PEQUEÑO FRAGMENTE DE CABECERA
    SOMOS UNA COMUNIDAD DE AMIGOS QUE NOS UNIMOS EN POS DE AYUDAR  
    A NUSTROS AMIGOS PELUDOS A CONSEGUIR SU HOGAR, O ASU VEZ AYUDAR 
    A QUIENES TIENEN MÁSCOTAS PARA DAR EN ADOPCIÓN. NUESTRO MOTOR ES EL ALTRUISMO, Y LA MEJORA DE CALIDAD DE NUESTROS
    AMIGOS LOS PERROS, CON UN SEGUIMIENTO SEGURO DE LA UBICACIÓN DE EN UN CORRECTO <HOGAR>
      NOS AYUDAS? BOTON ADOPTAR
LOGITOS EN CADA CARD CON TÍTUOLOS
      TENEMOS EL ENCABEZADO LAS TRES CARTAS VAN EN UN CARROUSEL
TRES CARTAS 
VISITA NUESTROS PELUDOS BOTON LINK, EN DONDE TENDRAS ACCESO A MAS INFORMACIÓ<N>
  CARTA DOS <INGRESA>
    YA SEA PREVIO REGISTRO / LOGIN SE TE HABILITARA LA INFORMACIÓN DEL HOSPEDADOR DEL PERRO(QUIEN DA EN ADOPCIÓN)

    CARTA TRES CON LA INFORMACIÓN BRINDADA <CONTACTA>
      CARTA CUATRO LLENA EL FORMULARIO Y CARGA TU PERRO ENCONTRADO EN ADOPCIÓ<N>
        MOSTRAREMOS AL MISMO EN PROCURA DE UN PRONTO ADOPTANTE Y FELIZ HOGAR PARA ÉL
      </N>
    </CONTACTA>
  </INGRESA>
</N>
    (BOTON AODPTAR)
   </div>
  );
}

export default About;
